services:
  - type: web
    name: gamzstockz-ml-api
    runtime: python
    rootDir: ML_services/api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: NEWS_API_KEY
        sync: false         # you'll set this in Render dashboard
      - key: PYTHON_VERSION
        value: "3.11.0"
    healthCheckPath: /health
    autoDeploy: true
